version: "2"

networks:
  main_traffic:

services:
  web:
    build: ./app
    ports:
      - "81:8080"
    networks:
      main_traffic:
        aliases:
          - webserver
  db:
    image: postgres:latest
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
    networks:
      main_traffic:
        aliases:
          - pgdb
  pgadmin:
    # default user: pgadmin4@pgadmin.org
    # default password: admin
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    networks:
      main_traffic:
        aliases:
          - pgadmin
